project 'JQFlowView.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JQFlowView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage'
  # Pods for JQFlowView

  target 'JQFlowViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JQFlowViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
